module TableCompilator
  module Compatibility
    ADJACENT_CELL_MARKER = "⬱"
    ADJACENT_CLOSING_MARKER = "↥"
    ADJACENT_MARKER = "↞"
    ADJACENT_ROW_MARKER = "⇇"

    BELOW_CONTENT_MARKER = "⟱"
    BELOW_OPENING_MARKER = "⇣"
    BELOW_PARAGRAPH_MARKER = "⇊"

    CONTENT_END = "◍"

    EMPTY = "◌"

    IRREGULAR_MARKER = "◜"

    PLACEHOLDER_HTML_ADJACENT_CELL_MARKER = "&#11057;"
    PLACEHOLDER_HTML_ADJACENT_CLOSING_MARKER = "&#8613;"
    PLACEHOLDER_HTML_ADJACENT_MARKER = "&#8647;"
    PLACEHOLDER_HTML_ADJACENT_ROW_MARKER = "&#8606;"
    PLACEHOLDER_HTML_BELOW_OPENING_MARKER = "&#8675;"
    PLACEHOLDER_HTML_BELOW_PARAGRAPH_MARKER = "&#8650;"
    PLACEHOLDER_HTML_BELOW_CONTENT_MARKER = "&#10225;"
    PLACEHOLDER_HTML_CONTENT_END = "&#9677;"
    PLACEHOLDER_HTML_EM_SPACE = "&#9697;"
    PLACEHOLDER_HTML_EMPTY_MARKER = "&#8615;"
    PLACEHOLDER_HTML_IRREGULAR_MARKER = "&#9692;"
    PLACEHOLDER_HTML_RETURN = "&#9166;"

    CELL_IGNORABLE_MARKERS = [
      PLACEHOLDER_HTML_ADJACENT_MARKER,
      PLACEHOLDER_HTML_ADJACENT_ROW_MARKER,
      PLACEHOLDER_HTML_BELOW_CONTENT_MARKER,
      PLACEHOLDER_HTML_BELOW_OPENING_MARKER,
      PLACEHOLDER_HTML_BELOW_PARAGRAPH_MARKER,
      PLACEHOLDER_HTML_CONTENT_END,
      PLACEHOLDER_HTML_IRREGULAR_MARKER,
      BELOW_OPENING_MARKER,
      BELOW_PARAGRAPH_MARKER,
      IRREGULAR_MARKER
    ]

    FIRST_CELL_IGNORABLE_MARKERS = [
      BELOW_PARAGRAPH_MARKER,
      PLACEHOLDER_HTML_ADJACENT_CLOSING_MARKER,
      PLACEHOLDER_HTML_BELOW_CONTENT_MARKER,
      PLACEHOLDER_HTML_BELOW_PARAGRAPH_MARKER
    ]
  end
end
