module TableCompilator
  module Compatibility
    ADJACENT_CELL_MARKER = "⬱"
    ADJACENT_MARKER = "↞"
    ADJACENT_ROW_MARKER = "⇇"

    BELOW_OPENING_MARKER = "⇣"
    BELOW_PARAGRAPH_MARKER = "⇊"

    EMPTY = "◌"

    IRREGULAR_MARKER = "◜"

    PLACEHOLDER_HTML_ADJACENT_CELL_MARKER = "&#11057;"
    PLACEHOLDER_HTML_BELOW_OPENING_MARKER = "&#8675;"
    PLACEHOLDER_HTML_BELOW_PARAGRAPH_MARKER = "&#8650;"
    PLACEHOLDER_HTML_ADJACENT_ROW_MARKER = "&#8606;"
    PLACEHOLDER_HTML_EM_SPACE = "&#9697;"
    PLACEHOLDER_HTML_IRREGULAR_MARKER = "&#9692;"
    PLACEHOLDER_HTML_RETURN = "&#9166;"
  end
end
